[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Nick Pfundstein <nickpfundstein@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
base64 = "0.10.0"
bit-vec = "0.5.0"
openssl = "0.10.23"
